#!/bin/bash
if [[ -z "$(grep er-mrhat-plat /etc/modules)"  ]];
then 
    echo "Adding er-mrhat-plat to /etc/modules ..."
    echo 'er-mrhat-plat' >> /etc/modules
    depmod
fi

echo "Please add 'dtoverlay=mrhat-platform' if needed, then reboot ..."


